# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='target',
            field=models.FloatField(default=0.0),
        ),
    ]
